fix typos in new Chocolatey feature 'choco export'
gep13/choco pull request #1
Opened 2019-05-13 20:08 UTC by mwallner

2019-05-17 11:04 UTC, gep13 requested changes
Small change before merging, thanks!

2019-05-17 11:04 UTC, gep13 commented on src/chocolatey/infrastructure.app/commands/ChocolateyExportCommand.cs
> +If you find other exit codes that we have not yet been documented, please
@mwallner can you remove this change, as it doesn't actually make sense the way you have written it.  Once changed, we can get this merged in.

2019-06-03 19:42 UTC, closed without merging

2019-06-03 21:16 UTC, gep13 commented
@mwallner thanks for closing this off.  It was easier to redo the commit locally during the last stream, but I attributed you on the commit, so you will get some "internet points" for your help 😄

2019-06-03 21:18 UTC, mwallner commented
:-D that wouldn't be neccessary, but I do appreciate it ;-)